{{- if .Values.env.config}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.name}}
data:
{{.Values.env.config | toYaml | indent 2}}
---
{{- end}}

{{- if .Values.env.secrets}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}
stringData:
{{.Values.env.secrets | toYaml | indent 2}}
---
{{- end}}

{{- if .Values.dockercfg}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-dockercfg
  annotations:
    harness.io/skip-versioning: true
data:
  .dockercfg: {{.Values.dockercfg}}
type: kubernetes.io/dockercfg
---
{{- end}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  labels:
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "teastore-recommender"
    tags.datadoghq.com/version: "1.3.8"
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: teastore
      run: {{.Values.name}}
  template:
    metadata:
      labels:
        app: teastore
        run: {{.Values.name}}
    spec:
      {{- if .Values.dockercfg}}
      imagePullSecrets:
      - name: {{.Values.name}}-dockercfg
      {{- end}}
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
        ports:
        - containerPort: {{.Values.serviceTargetPort}}
        {{- if or .Values.env.config .Values.env.secrets}}
      env:
        config:
          HOST_NAME: "teastore-recommender"
          REGISTRY_HOST: "teastore-registry" 
        - configMapRef:
            name: {{.Values.name}}
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_ENV
           valueFrom:
            fieldRef:
             fieldPath: metadata.labels['tags.datadoghq.com/env']
        - name: DD_SERVICE
         valueFrom:
            fieldRef:
             fieldPath: metadata.labels['tags.datadoghq.com/service']
        - name: DD_VERSION
         valueFrom:
            fieldRef:
             fieldPath: metadata.labels['tags.datadoghq.com/version']
        - name: DD_PROFILING_ENABLED
          value: "true"
        - name: DD_LOGS_INJECTION
          value: "true"
        {{- if .Values.env.secrets}}
        - secretRef:
            name: {{.Values.name}}
        {{- end}}
        {{- end}}

