apiVersion: v1
kind: Service
metadata:
  name: teastore-webui
  labels:
    app: teastore
    run: teastore-webui
spec:
  type: NodePort
  ports:
  - port: 30080
    protocol: TCP
  selector:
    app: teastore
    run: teastore-webui
